server {
    listen 80;
    
    # This matches the volume mounted in docker-compose
    root /usr/share/nginx/html;

    # Automatically load the index file when visiting the root URL
    location / {
        index pages/index.html;
        try_files $uri $uri/ /pages/index.html;
    }

    # Ensure static assets (CSS, JS) are served correctly
    location /static/ {
        try_files $uri =404;
    }
}